#!/usr/bin/env bash

npx validate-branch-name -r '^(main|prod|stg|dev)$|^(feature|fix|hotfix)/.+$'

# echo "formatting tf files"
# cd $(git rev-parse --show-toplevel)
# terraform  fmt -write=true -recursive; git add . 

# kubectl context must be configured and aws logged in
pytest
black --check .

gitleaks git --staged
